language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    secure: UVvBxNf6tsDjCT6NFADBEpSH2Oeh5ikTh+RugVuW+gMhnF6cnapSO9YJE5RpVu8RjIPZInDiEyrFjufHvbLEdr/Zj9AMHJruDpKjxkIV9dnOre6z3pAF15DPTp5prD6xaJVyHHkLiFufR2E3QTVFSiwJNC9/LAmE8D5CIa6+RSs=

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - 'if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'

install:
  - composer require php-coveralls/php-coveralls --no-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $TRAVIS_PHP_VERSION == "7.4" ]]; then sh generate-api.sh; fi;'

notifications:
  email: false
